language: java

# To increase the memory size available during Travis build.
sudo: required

env:
  global:
    # Encrypted `CODACY_PROJECT_TOKEN` variable according to:
    # https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables
    - secure: wfdcbEHue3COzF21Uxo4DPd+dwutDRrKGrIDc6HajQIxGSqg5UV5XyaRRomCwzvE0dRGCePTBv0kmTCISkV7ou/32P19YhTyhrL/UayX4pG3uofTuBrpy8v0gvbQOE2+ajzLhHXrVnXjcFqEQPJjLATOp3EPIvC+EBW+/e+9fHD/4YdryRgS0BdN5+TbhHVf3j4zLntIyUGBXjVbzo3QOtgYK91u7RnpAVpN9SZZQtg/fyYpFniqnB5ULAnPEaumSny7HvZYSq9G4Q12do+NB5jfc7OCehzlqgIK1PsjWawfWwBFB3Q2l1Qj5h+gSssuIx3tZsj0MNI/MsEvMKxfNdVPCmQUxZUP7fk43eZUdf8LiABzCQQHGv3RkwwAYJlfeZm/ufvVA0Lu4OkPJJNLqjEQEUOjWVWG02qFOxBMBCw0LE9KuoB07zA6V+NVi3yCKuPkUgu+mWYqJ3buFGDRlgY1C34EHLCe+G4jFXu/NFuTMobCFnQP6kUPu63ZFpELes4EtfzfmiDVC2+eRjDAYtevS4uHnsTUsz7vABBUMHOqUcvXNXJGXNTYLkB5MSdE+MXjhDgkSGg9GHatAQx8Y0f7chisdNJZ8+cmLstOnZkTQLuLxpjwCzTED+i/5yrJ775dIbMetQYzeoTaQaXOes6hDR51w8Lfdqq4E332DrI=
    # Encrypted `GCS_SECRET` variable.
    - secure: "i8MhONZu7QjyM2V887A1Tydr1WMqQP5jJZNjIJjc1Uae8F0/z8cJZIZ1hstodN7FpoR4VF92zyhUwbt6fz/dsdPEJFccsiMlEc9vlqecQCd267160wgRZneaB6Xe/y/EUmq9XsGdn/k1Ey+QZwX9au/8RU191v+fDsCtMRYXzyEa/BvbQuSwuYRgQDxTAxuJgTmG5Sxl9jWqKw1BfxUcEoErc/jqymU58w6z2TxKxVzIXT29Jy/Z12VuSiS8opigSrIP8e/1fctC84wI7S52mext2ZfhPYSTHFKS+xg1vQDYPb8m5aomL8E6Of7hVD5BTnEnyjj+/Gr63GAzHXtkHhWoxo+vB+xBFfDu8wxM5Aqna3H7LMDD5kGCxQEz8qmzHBHMAhLnhsRzjNVu2+tLCZdeMN88Ud2uemL2SCAcR8Juleg7DGMj3D0SAbPyUH3+9yYYWzSg6iaxgTdHBnJ+uXUJp0Nu+M2EK6Kl+pYAsCLVfZRPGaajFXVnJEPPeSr2PYzk7F4pIzgn/E8AtYEJ0gcEbjoTItS8EjliJKDXM4HdkluXBFLvzIH1O1nCtxKNv4UkUmPhFbfHrPXDcsYq2zsEe+NkvsJlxjAwYnOMkT4NLiEsec1a7K9bBC+iQA9e8rriMbu6/1w63JErQyx05avPjgO8XRDK8hxTf4rhBmY="

before_install:
  - chmod +x gradlew

script:
  - ./gradlew check --stacktrace

  # Decrypt and unarchive Maven and Google Cloud Storage credentials.
  - openssl aes-256-cbc -K $encrypted_88ad5eb2de44_key -iv $encrypted_88ad5eb2de44_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

  - ./gradlew cleanGCS --info

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./scripts/publish-artifacts.sh
  - ./scripts/publish-artifacts.sh

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)
  - chmod +x ./scripts/report-coverage.sh
  - ./scripts/report-coverage.sh

after_script:
  - chmod +x ./scripts/upload-artifacts.sh
  - ./scripts/upload-artifacts.sh
