language: java

# To increase the memory size available during Travis build.
sudo: required

env:
  global:
    # Encrypted `GCS_SECRET` variable.
    - secure: "i8MhONZu7QjyM2V887A1Tydr1WMqQP5jJZNjIJjc1Uae8F0/z8cJZIZ1hstodN7FpoR4VF92zyhUwbt6fz/dsdPEJFccsiMlEc9vlqecQCd267160wgRZneaB6Xe/y/EUmq9XsGdn/k1Ey+QZwX9au/8RU191v+fDsCtMRYXzyEa/BvbQuSwuYRgQDxTAxuJgTmG5Sxl9jWqKw1BfxUcEoErc/jqymU58w6z2TxKxVzIXT29Jy/Z12VuSiS8opigSrIP8e/1fctC84wI7S52mext2ZfhPYSTHFKS+xg1vQDYPb8m5aomL8E6Of7hVD5BTnEnyjj+/Gr63GAzHXtkHhWoxo+vB+xBFfDu8wxM5Aqna3H7LMDD5kGCxQEz8qmzHBHMAhLnhsRzjNVu2+tLCZdeMN88Ud2uemL2SCAcR8Juleg7DGMj3D0SAbPyUH3+9yYYWzSg6iaxgTdHBnJ+uXUJp0Nu+M2EK6Kl+pYAsCLVfZRPGaajFXVnJEPPeSr2PYzk7F4pIzgn/E8AtYEJ0gcEbjoTItS8EjliJKDXM4HdkluXBFLvzIH1O1nCtxKNv4UkUmPhFbfHrPXDcsYq2zsEe+NkvsJlxjAwYnOMkT4NLiEsec1a7K9bBC+iQA9e8rriMbu6/1w63JErQyx05avPjgO8XRDK8hxTf4rhBmY="
    - GRADLE_OPTS="-Xmx2G"

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build check --debug
  - cd ./tools/smoke-tests
  - ./gradlew check --stacktrace
  - cd ../..

  # Decrypt and unarchive Maven and Google Cloud Storage credentials.
  - openssl aes-256-cbc -K $encrypted_90b6979075fc_key -iv $encrypted_90b6979075fc_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./config/scripts/publish-artifacts.sh
  - ./config/scripts/publish-artifacts.sh

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - chmod +x ./config/scripts/upload-artifacts.sh
  - ./config/scripts/upload-artifacts.sh
