#!/usr/bin/env bash

./config/pull

echo "Copying buildSrc to base-validating-builders"
cp -R ./buildSrc ./base-validating-builders

echo "Copying buildSrc to smoke-tests"
cp -R ./buildSrc ./tools/smoke-tests
