/*
 * Copyright 2021, TeamDev. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Redistribution and use in source and/or binary forms, with or without
 * modification, must retain the above copyright notice and the following
 * disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package io.spine.tools.code.fs;

import io.spine.annotation.Internal;

import java.nio.file.Path;

import static com.google.common.base.Preconditions.checkNotNull;

/**
 * Enumerates default names for project structure directories.
 */
public enum DirectoryName {

    /** The directory for the handcrafted source code. */
    src,

    /**
     * The directory of the generated source code.
     *
     * <p>The standard location for such a directory is under the module root.
     * In other words, this directory is a sibling for {@link #src}.
     */
    generated,

    /** Contains production artifact code. */
    main,

    /** Contains test artifact code. */
    test,

    /** Contains source code in Java. */
    java,

    /** Contains source code in Kotlin. */
    kotlin,

    /** Contains program resources. */
    resources,

    /** The directory with Dart and JS source code. */
    lib,

    /** Spine-specific generated code. */
    spine,

    /** Code generated by gRPC. */
    grpc,

    /** Build results are placed under this directory. */
    build,

    /** Contains Protobuf descriptor set files produced during the build. */
    descriptors,

    /**
     * Internal directory name for storing temporary build artifacts.
     *
     * @see DefaultPaths#tempArtifacts()
     */
    @Internal
    dotSpine(".spine");

    private final String value;

    DirectoryName() {
        this.value = name();
    }

    DirectoryName(String value) {
        this.value = value;
    }

    /**
     * Creates a path to the directory with this name under the given parent.
     */
    public Path under(Path parent) {
        checkNotNull(parent);
        Path result = parent.resolve(value);
        return result;
    }

    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return value;
    }
}
