name: codegen_test
homepage: https://spine.io
author: Spine Event Engine <spine-developers@teamdev.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  protobuf: ^0.14.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
