/*
 * Copyright 2019, TeamDev. All rights reserved.
 *
 * Redistribution and use in source and/or binary forms, with or without
 * modification, must retain the above copyright notice and the following
 * disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

import 'package:code_builder/code_builder.dart';
import 'package:dart_code_gen/google/protobuf/descriptor.pb.dart';
import 'package:dart_code_gen/spine/options.pb.dart';

import 'constraint_violation.dart';
import 'imports.dart';
import 'validator_factory.dart';

/// Factory of validation code for a given message field.
///
class FieldValidatorFactory {

    /// The [ValidatorFactory] for the declaring message type.
    final ValidatorFactory validatorFactory;

    /// The field to validate.
    final FieldDescriptorProto field;

    FieldValidatorFactory._(this.validatorFactory, this.field);

    /// Creates a new `FieldValidatorFactory` for the given field.
    factory FieldValidatorFactory.forField(FieldDescriptorProto field, ValidatorFactory factory) {
        var type = field.type;
        switch (type) {
            case FieldDescriptorProto_Type.TYPE_STRING:
                return new _StringValidatorFactory(factory, field);
            case FieldDescriptorProto_Type.TYPE_FLOAT:
                return new _FloatValidatorFactory(factory, field);
        }
        return null;
    }

    /// Generates validator code for the specified field.
    ///
    /// The validator obtains the field value via the given [fieldValue] expression.
    ///
    /// If any constrains violations are discovered, they are added to
    /// the [ValidatorFactory.violationList] of the [validatorFactory].
    ///
    Code createFieldValidator(Expression fieldValue) {
        var statements = _rules()
            .map((r) => r.eval(fieldValue))
            .map((expression) => expression.statement)
            .toList();
        return statements.isNotEmpty
               ? Block.of(statements)
               : null;
    }

    /// Obtains validation rules to apply to the field..
    Iterable<_Rule> _rules() => null;

    /// Generates an expression which constructs a `ConstraintViolation` for a missing required
    /// field.
    Expression _requiredMissing() {
        return violationRef.call([literalString('Field must be set.'),
                                  literalString(validatorFactory.fullTypeName),
                                  literalList([field.name])]);
    }
}

/// A validation rule.
///
/// Represents an atomic constraint which should be followed by a message field.
///
/// Typically, one rule represents one validation option for a given field type.
///
class _Rule {

    final LazyCondition _condition;
    final LazyViolation _violation;
    final Expression _targetViolationList;

    /// Creates a new rule.
    ///
    /// The [_condition] expression is evaluated to find out if the rule is broken or not.
    ///
    /// The [_violation] expression is evaluated to obtain a `ConstraintViolation` if the rule is
    /// broken.
    ///
    /// The [_targetViolationList] is an expression which represents a list which accumulates all
    /// the `ConstraintViolation`s. If the rule is broken, the violation generated by [_violation]
    /// is added to the list.
    ///
    _Rule(this._condition, this._violation, this._targetViolationList);

    /// Produces a ternary operator which creates a new violation if the string is empty.
    ///
    /// ```dart
    /// validationCondition(<Field value>)
    ///     ? violations.add(_violation(..))
    ///     : null;
    /// ```
    ///
    /// `code_builder` does not support `if` statements, so a ternary conditional operator has to
    /// be used.
    ///
    Expression eval(Expression fieldValue) {
        var ternaryOperator = _condition(fieldValue).conditional(
            _targetViolationList
                .property('add')
                .call([_violation(fieldValue)]),
            literalNull);
        return ternaryOperator;
    }
}

/// A function of a field value expresion to a `ConstraintViolation` expression.
typedef Expression LazyViolation(Expression fieldValue);

/// A function of a field value expresion to a boolean expression representing a constraint.
typedef Expression LazyCondition(Expression fieldValue);

/// A [FieldValidatorFactory] for `string` fields.
///
/// Currently, the only supported option is `(required)`.
///
class _StringValidatorFactory extends FieldValidatorFactory {

    _StringValidatorFactory(ValidatorFactory validatorFactory, FieldDescriptorProto field)
        : super._(validatorFactory, field);

    Iterable<_Rule> _rules() {
        var rules = <_Rule>[];
        if (field.options.hasExtension(Options.required)) {
            var requiredString = _Rule((v) => v.property('isEmpty'),
                                       (v) => _requiredMissing(),
                                       validatorFactory.violationList);
            rules.add(requiredString);
        }
        return rules;
    }
}

/// A [FieldValidatorFactory] for `float` fields.
///
/// Currently, the supported options are `(min)` and `(max)`.
///
class _FloatValidatorFactory extends FieldValidatorFactory {

    _FloatValidatorFactory(ValidatorFactory validatorFactory, FieldDescriptorProto field)
        : super._(validatorFactory, field);

    Iterable<_Rule> _rules() {
        var rules = <_Rule>[];
        var options = field.options;
        if (options.hasExtension(Options.min)) {
            var min = options.getExtension(Options.min) as MinOption;
            var bound = double.parse(min.value);
            var exclusive = min.exclusive;
            var literal = literalNum(bound);
            var check = exclusive
                        ? (Expression v) => v.lessOrEqualTo(literal)
                        : (Expression v) => v.lessThan(literal);
            var requiredString = _Rule((v) => check(v),
                                       _outOfBound,
                                       validatorFactory.violationList);
            rules.add(requiredString);
        }
        if (options.hasExtension(Options.max)) {
            var max = options.getExtension(Options.max) as MaxOption;
            var bound = double.parse(max.value);
            var exclusive = max.exclusive;
            var literal = literalNum(bound);
            var check = exclusive
                        ? (Expression v) => v.greaterOrEqualTo(literal)
                        : (Expression v) => v.greaterThan(literal);
            var requiredString = _Rule((v) => check(v),
                                       _outOfBound,
                                       validatorFactory.violationList);
            rules.add(requiredString);
        }
        return rules;
    }

    // TODO:2019-10-14:dmytro.dashenkov: Support custom error messages based on the option value.
    // https://github.com/SpineEventEngine/base/issues/482
    Expression _outOfBound(Expression value) {
        var param = 'v';
        var standardPackage = validatorFactory.properties.standardPackage;
        var floatValue = refer('FloatValue', protoWrappersImport(standardPackage))
            .newInstance([])
            .property('copyWith')
            .call([Method((b) => b
            ..requiredParameters.add(Parameter((b) => b.name = param))
            ..body = refer(param)
                .property('value')
                .assign(value)
                .statement).closure]);
        var any = refer('Any', protoAnyImport(standardPackage)).property('pack').call([floatValue]);
        return violationRef.call([literalString('Float field is out of bound.'),
                                  literalString(validatorFactory.fullTypeName),
                                  literalList([field.name]),
                                  any]);
    }
}
