/*
 * Copyright 2021, TeamDev. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Redistribution and use in source and/or binary forms, with or without
 * modification, must retain the above copyright notice and the following
 * disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package io.spine.tools.java.fs;

import io.spine.code.fs.SourceCodeDirectory;
import io.spine.tools.code.fs.ArtifactSources;
import io.spine.tools.code.fs.DefaultPaths;

import static io.spine.tools.code.fs.DirectoryName.generated;
import static io.spine.tools.code.fs.DirectoryName.grpc;
import static io.spine.tools.code.fs.DirectoryName.resources;
import static io.spine.tools.code.fs.DirectoryName.spine;

/**
 * A root directory for the generated code.
 */
public final class Generated extends JavaSrc {

    Generated(DefaultPaths parent) {
        super(parent, generated);
    }

    /**
     * Spine-generated source code directory.
     */
    public SourceCodeDirectory mainSpine() {
        return new ArtifactSources(main(), spine);
    }

    /**
     * Spine-generated source code directory for tests.
     */
    public SourceCodeDirectory testSpine() {
        return new ArtifactSources(test(), spine);
    }

    /**
     * The directory for the source code generated by gRPC.
     */
    public SourceCodeDirectory mainGrpc() {
        return new ArtifactSources(main(), grpc);
    }

    /**
     * The directory for the test source code generated by gRPC.
     */
    public SourceCodeDirectory testGrpc() {
        return new ArtifactSources(test(), grpc);
    }

    /**
     * The directory for generated resources.
     */
    public SourceCodeDirectory mainResources() {
        return new ArtifactSources(main(), resources);
    }

    /**
     * The directory for generated test resources.
     */
    public SourceCodeDirectory testResources() {
        return new ArtifactSources(test(), resources);
    }
}
