/*
 * Copyright 2020, TeamDev. All rights reserved.
 *
 * Redistribution and use in source and/or binary forms, with or without
 * modification, must retain the above copyright notice and the following
 * disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package io.spine.base.entity;

import com.google.errorprone.annotations.Immutable;
import io.spine.annotation.FirstGenericParameter;
import io.spine.annotation.GeneratedMixin;
import io.spine.base.KnownMessage;

/**
 * A common interface for entity state messages.
 *
 * <p>Any message that defines an {@code (entity)} option with a valid {@code kind} is marked with
 * this interface by the Model Compiler.
 *
 * <p>The first field of the entity state message is treated as its identifier. It is a convention
 * that has two goals:
 *
 * <ol>
 *     <li>The definition of an entity state always starts with its ID with no extra Protobuf
 *     options. This way it's feels easy and natural to read the code.

 *     <li>Developers don't forget to specify which of the fields declared in Protobuf corresponds
 *     to the entity ID.
 * </ol>
 *
 * <p>At codegen-time the Model Compiler substitutes the generic parameter {@code <I>} with
 * an actual type of the first field of the entity state message.
 *
 * @param <I>
 *         the type of entity identifiers
 * @see io.spine.code.proto.EntityStateOption
 */
//TODO:2020-06-10:alex.tymchenko: kill this warning?
//@SuppressWarnings("InterfaceNeverImplemented") // Implemented in the dependent repos.
@SuppressWarnings("unused")     // <I> is used in scope of the code generated by the Model Compiler.
@Immutable
@GeneratedMixin
@FirstGenericParameter(is = FirstMessageField.class)
public interface EntityState<I> extends KnownMessage {

}
