name: dart_code_gen
description: A command line application for generating validation code based on Spine validation options.
version: 0.1.0
homepage: https://spine.io
author: Spine Event Engine <spine-developers@teamdev.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: 1.5.2
  protobuf: ^1.0.0
  fixnum: ^0.10.9
  code_builder: ^3.2.0
  dart_style: 1.3.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  dart_code_gen: main
