/*
 * Copyright 2018, TeamDev. All rights reserved.
 *
 * Redistribution and use in source and/or binary forms, with or without
 * modification, must retain the above copyright notice and the following
 * disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package io.spine.tools.protojs.field;

import com.google.protobuf.Descriptors.FieldDescriptor;
import io.spine.tools.protojs.code.JsGenerator;
import io.spine.tools.protojs.field.checker.FieldValueChecker;
import io.spine.tools.protojs.field.parser.FieldValueParser;

import static com.google.common.base.Preconditions.checkNotNull;
import static io.spine.tools.protojs.field.Fields.isMap;
import static io.spine.tools.protojs.field.Fields.isRepeated;
import static io.spine.tools.protojs.field.Fields.keyDescriptor;
import static io.spine.tools.protojs.field.Fields.valueDescriptor;
import static io.spine.tools.protojs.field.checker.FieldValueCheckers.checkerFor;
import static io.spine.tools.protojs.field.parser.FieldValueParsers.parserFor;

/**
 * The helper class which provides the {@link FieldHandler} implementation for the given
 * {@linkplain FieldDescriptor field}.
 *
 * <p>The caller should also specify the {@link JsGenerator} which will store all the code
 * generated by the handler.
 *
 * @author Dmytro Kuzmin
 */
public final class FieldHandlers {

    /** Prevents instantiation of this utility class. */
    private FieldHandlers() {
    }

    /**
     * Creates a {@code FieldHandler} for the given field descriptor and {@link JsGenerator}.
     *
     * @param field
     *         the descriptor of the field to be handled
     * @param jsGenerator
     *         the {@code JsGenerator} to accumulate all the generated code
     * @return the new {@code FieldHandler} of the appropriate type
     */
    public static FieldHandler createFor(FieldDescriptor field, JsGenerator jsGenerator) {
        checkNotNull(field);
        checkNotNull(jsGenerator);
        if (isMap(field)) {
            return mapHandler(field, jsGenerator);
        }
        if (isRepeated(field)) {
            return repeatedHandler(field, jsGenerator);
        }
        return singularHandler(field, jsGenerator);
    }

    /**
     * Creates the {@linkplain MapFieldHandler handler} for the {@code map} field.
     *
     * @implNote
     * The creation logic is different from all other handlers.
     *
     * <p>As the {@code map} field is always a message of type {@code ...Entry}, we create
     * {@link FieldValueChecker} and {@link FieldValueParser} for it's field with name
     * {@code "value"} (whose type corresponds to the {@code map} value).
     *
     * <p>The key also has to be parsed via separate {@code FieldValueParser}, as in JSON it is
     * always converted to a {@code string}. So we create additional {@code FieldValueParser} for
     * the {@code ...Entry.key} field.
     */
    private static FieldHandler mapHandler(FieldDescriptor field, JsGenerator jsGenerator) {
        FieldValueParser keyParser = mapKeyParser(field, jsGenerator);
        FieldValueParser valueParser = mapValueParser(field, jsGenerator);
        FieldValueChecker valueChecker = mapValueChecker(field, jsGenerator);

        FieldHandler handler = MapFieldHandler
                .newBuilder()
                .setField(field)
                .setChecker(valueChecker)
                .setKeyParser(keyParser)
                .setParser(valueParser)
                .setJsGenerator(jsGenerator)
                .build();
        return handler;
    }

    /**
     * Creates the {@linkplain RepeatedFieldHandler handler} for the {@code repeated} proto field.
     */
    private static FieldHandler repeatedHandler(FieldDescriptor field, JsGenerator jsGenerator) {
        FieldValueChecker checker = checkerFor(field, jsGenerator);
        FieldValueParser parser = parserFor(field, jsGenerator);

        FieldHandler handler = RepeatedFieldHandler
                .newBuilder()
                .setField(field)
                .setChecker(checker)
                .setParser(parser)
                .setJsGenerator(jsGenerator)
                .build();
        return handler;
    }

    /**
     * Creates the {@linkplain SingularFieldHandler handler} for the ordinary proto field.
     */
    private static FieldHandler singularHandler(FieldDescriptor field, JsGenerator jsGenerator) {
        FieldValueChecker checker = checkerFor(field, jsGenerator);
        FieldValueParser parser = parserFor(field, jsGenerator);

        FieldHandler handler = SingularFieldHandler
                .newBuilder()
                .setField(field)
                .setChecker(checker)
                .setParser(parser)
                .setJsGenerator(jsGenerator)
                .build();
        return handler;
    }

    /**
     * Creates a {@code FieldValueChecker} for the value of the map field.
     */
    private static FieldValueChecker
    mapValueChecker(FieldDescriptor field, JsGenerator jsGenerator) {
        FieldDescriptor valueDescriptor = valueDescriptor(field);
        FieldValueChecker checker = checkerFor(valueDescriptor, jsGenerator);
        return checker;
    }

    /**
     * Creates a {@code FieldValueParser} for the key of the map field.
     */
    private static FieldValueParser mapKeyParser(FieldDescriptor field, JsGenerator jsGenerator) {
        FieldDescriptor keyDescriptor = keyDescriptor(field);
        FieldValueParser parser = parserFor(keyDescriptor, jsGenerator);
        return parser;
    }

    /**
     * Creates a {@code FieldValueParser} for the value of the map field.
     */
    private static FieldValueParser mapValueParser(FieldDescriptor field, JsGenerator jsGenerator) {
        FieldDescriptor valueDescriptor = valueDescriptor(field);
        FieldValueParser parser = parserFor(valueDescriptor, jsGenerator);
        return parser;
    }
}
