// Generated by Spine Proto Dart Gradle plugin.
//
// https://github.com/SpineEventEngine/base
//
// Do NOT edit this file manually.
//

import "package:protobuf/builder_info.dart";
import "package:protobuf/generated_message.dart";

import "package:protobuf/protobuf.dart";

// @import@


Map<string, BuilderInfo> _typeUrlToInfo = {
  // @type-to-info@

};

Map<GeneratedMessage, string> _defaultToTypeUrl = {
  // @message-to-type@

};
