// Generated by Spine Proto Dart Gradle plugin.
//
// https://github.com/SpineEventEngine/base
//
// Do NOT edit this file manually.
//

import "package:protobuf/protobuf.dart";

// @import@


Map<String, BuilderInfo> typeUrlToInfo = {
  // @type-to-info@

};

Map<GeneratedMessage, String> defaultToTypeUrl = {
  // @message-to-type@

};
