// Generated by Spine Proto Dart Gradle plugin.
//
// https://github.com/SpineEventEngine/base
//
// Do NOT edit this file manually.
//

import "package:protobuf/protobuf.dart";

// Protobuf message imports:
import 'spine/test/tools/dart/test.pb.dart' as _spine_test_tools_dart_test;


Map<String, BuilderInfo> typeUrlToInfo = {
  // Map of type URLs to BuilderInfos:
'type.spine.io/spine.test.tools.DartSmokeTest': _spine_test_tools_dart_test.DartSmokeTest().info_,
'type.spine.io/spine.test.tools.First': _spine_test_tools_dart_test.First().info_,
'type.spine.io/spine.test.tools.First.Second': _spine_test_tools_dart_test.First_Second().info_,
'type.spine.io/spine.test.tools.First.Second.Third': _spine_test_tools_dart_test.First_Second_Third().info_,

};

Map<GeneratedMessage, String> defaultToTypeUrl = {
  // Map of default message instances to type URLs:
_spine_test_tools_dart_test.DartSmokeTest(): 'type.spine.io/spine.test.tools.DartSmokeTest',
_spine_test_tools_dart_test.First(): 'type.spine.io/spine.test.tools.First',
_spine_test_tools_dart_test.First_Second(): 'type.spine.io/spine.test.tools.First.Second',
_spine_test_tools_dart_test.First_Second_Third(): 'type.spine.io/spine.test.tools.First.Second.Third',

};
