/*
 * Copyright 2018, TeamDev. All rights reserved.
 *
 * Redistribution and use in source and/or binary forms, with or without
 * modification, must retain the above copyright notice and the following
 * disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package io.spine.code;

import io.spine.code.proto.Directory;

import java.io.File;
import java.nio.file.Path;

import static com.google.common.base.Preconditions.checkNotNull;
import static io.spine.code.proto.FileDescriptors.KNOWN_TYPES;

/**
 * This class represents a default directory structure for a Spine-based project.
 *
 * <p>It helps resolving names of the directories and files under the project directory.
 * It is expected that for most projects, the default values of paths remain unchanged.
 *
 * <p>The default project structure is based on the standard Maven/Gradle project conventions,
 * with the following directories under the project root:
 *
 * <ul>
 * <li>{@code src/main} — manually written code production code, with {@code java} and
 * {@code proto} sub-directories.
 *
 * <li>{@code src/test} — the code of tests.
 *
 * <li>{@code generated} — computer-generated code, with sub-directories:
 * <ul>
 *     <li>{@code java} — the code generated by the Protobuf Compiler.
 *     <li>{@code gRPC} — the code generated by the gPRC Protobuf Compiler Plug-in.
 *     <li>{@code spine} — the code generated by the Spine Model Compiler.
 * </ul>
 * </li>
 *
 * <li>{@code .spine} — temporary build artifacts directory used by the Spine Model Compiler.
 * </ul>
 *
 * @author Alexander Yevsyukov
 */
public final class DefaultProject extends AbstractDirectory {

    /**
     * Default file name for descriptor set generated from the proto files under
     * the {@code main/proto} project directory.
     */
    private static final String MAIN_FILE = "main/" + KNOWN_TYPES;

    /**
     * Default file name for the descriptor set generated from the proto files under
     * the {@code test/proto} project directory.
     */
    private static final String TEST_FILE = "test/" + KNOWN_TYPES;

    /**
     * The Spine internal directory name for storing temporary build artifacts.
     *
     * @see #tempArtifacts()
     */
    private static final String TEMP_ARTIFACT_DIR = ".spine";

    private DefaultProject(Path path) {
        super(path);
    }

    public static DefaultProject at(Path root) {
        checkNotNull(root);
        DefaultProject result = new DefaultProject(root);
        return result;
    }

    public static DefaultProject at(File projectDir) {
        checkNotNull(projectDir);
        return at(projectDir.toPath());
    }

    public GeneratedRoot generated() {
        return new GeneratedRoot(this);
    }

    public File mainDescriptors() {
        BuildRoot build = BuildRoot.of(this);
        File result = build.descriptors()
                           .getPath()
                           .resolve(MAIN_FILE)
                           .toFile();
        return result;
    }

    @SuppressWarnings("DuplicateStringLiteralInspection") /* Tests use directory names. */
    public HandmadeCodeRoot src() {
        return new HandmadeCodeRoot(this, "src");
    }

    public File testDescriptors() {
        BuildRoot build = BuildRoot.of(this);
        File result = build.descriptors()
                           .getPath()
                           .resolve(TEST_FILE)
                           .toFile();
        return result;
    }

    /**
     * Obtains the directory for temporary Spine build artifacts.
     *
     * <p>Spine Gradle tasks may write some temporary files into this directory.
     *
     * <p>The directory is deleted on {@code :pre-clean"}.
     */
    public File tempArtifacts() {
        File result = new File(getPath().toFile(), TEMP_ARTIFACT_DIR);
        return result;
    }

    static class SourceDir extends SourceCodeDirectory {

        SourceDir(AbstractDirectory parent, String name) {
            super(parent.getPath()
                        .resolve(name));
        }
    }

    /**
     * A root source code directory in a project or a module.
     */
    @SuppressWarnings("DuplicateStringLiteralInspection") /* Tests use directory names. */
    public static class SourceRoot extends SourceDir {

        SourceRoot(DefaultProject parent, String name) {
            super(parent, name);
        }

        protected SourceDir getMain() {
            return new SourceDir(this, "main");
        }

        protected SourceDir getTest() {
            return new SourceDir(this, "test");
        }

        /**
         * A root directory for main Java code.
         */
        public io.spine.code.java.Directory mainJava() {
            return io.spine.code.java.Directory.rootIn(getMain());
        }

        /**
         * A root directory for test Java code.
         */
        public io.spine.code.java.Directory testJava() {
            return io.spine.code.java.Directory.rootIn(getTest());
        }
    }

    /**
     * A root source code directory for manually written code.
     *
     * <p>Adds a root directory for the proto code in addition to those exposed
     * by {@link SourceRoot}.
     */
    public static class HandmadeCodeRoot extends SourceRoot {

        private HandmadeCodeRoot(DefaultProject parent, String name) {
            super(parent, name);
        }

        /**
         * A root for the main proto code.
         */
        public Directory mainProto() {
            return Directory.rootIn(getMain());
        }

        /**
         * A root for the test proto code.
         */
        public Directory testProto() {
            return Directory.rootIn(getTest());
        }
    }

    /**
     * A root directory for the generated code.
     */
    public static final class GeneratedRoot extends SourceRoot {

        private static final String SPINE_DIR = "spine";
        private static final String GRPC_DIR = "grpc";
        private static final String RESOURCES_DIR = "resources";

        private GeneratedRoot(DefaultProject parent) {
            super(parent, "generated");
        }

        /**
         * Spine-generated source code directory.
         */
        public SourceCodeDirectory mainSpine() {
            return new SourceDir(getMain(), SPINE_DIR);
        }

        /**
         * Spine-generated source code directory for tests.
         */
        public SourceCodeDirectory testSpine() {
            return new SourceDir(getTest(), SPINE_DIR);
        }

        /**
         * The directory for the source code generated by gRPC.
         */
        public SourceCodeDirectory mainGrpc() {
            return new SourceDir(getMain(), GRPC_DIR);
        }

        /**
         * The directory for the test source code generated by gRPC.
         */
        public SourceCodeDirectory testGrpc() {
            return new SourceDir(getMain(), GRPC_DIR);
        }

        /**
         * The directory for generated resources.
         */
        public SourceCodeDirectory mainResources() {
            return new SourceDir(getMain(), RESOURCES_DIR);
        }

        /**
         * The directory for generated test resources.
         */
        @SuppressWarnings("unused") // reserved for future use.
        public SourceCodeDirectory testResources() {
            return new SourceDir(getTest(), RESOURCES_DIR);
        }
    }

    /**
     * The root directory for build output.
     */
    static final class BuildRoot extends AbstractDirectory {

        @SuppressWarnings("DuplicateStringLiteralInspection") // different meanings around the code.
        private static final String DIR_NAME = "build";

        private BuildRoot(DefaultProject module) {
            super(module.getPath()
                        .resolve(DIR_NAME));
        }

        static BuildRoot of(DefaultProject project) {
            return new BuildRoot(project);
        }

        private BuildDir descriptors() {
            return new BuildDir(this, "descriptors");
        }
    }

    static final class BuildDir extends AbstractDirectory {

        BuildDir(BuildRoot parent, String name) {
            super(parent.getPath()
                        .resolve(name));
        }
    }
}
