# Ensures that `buildSrc` directories are the same in all 3 projects:
#  - the root project;
#  - smoke tests;
#  - the `base-validating-builders` project.

name: Check buildSrc copies

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Check root and `tests` copies are the same.
        shell: bash
        run: ./script/same-dir.sh ./buildSrc ./tests/buildSrc

      - name: Check root and `base-validating-builders` copies are the same.
        shell: bash
        run: ./script/same-dir.sh ./buildSrc ./base-validating-builders/buildSrc
