name: Tests on Windows

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Pull config
        run: git submodule update --init --recursive

      - name: Run tests with Gradle
        run: gradlew.bat build

      - name: Set up Dart SDK
        run: choco install dart-sdk & refreshenv

      - name: Install Dart Protoc plugin
        run: pub.bat global activate protoc_plugin

      - name: Run smoke tests with Gradle
        run: cd tools\smoke-tests & gradlew.bat build
